# Generated by Django 3.0.6 on 2020-05-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200512_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='local_evento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Local do Evento'),
        ),
    ]
